DATASET:
  TRAIN_DATASET: 'mvor'
  TEST_DATASET: 'mvor'
  VIEW_IDS: [0,1,2]
  SAMPLING_RANGE: [5, 20]
  ALPHA: 0.1
TRAIN:
  BATCH_SIZE: 1
  BEGIN_EPOCH: 0
  END_EPOCH: 80
  RESUME: False
  CKP_PATH: ''
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP: [60]
  EDGE_ASSOCIATION: True
  REID: True
  GT_BOX: False
  THRESH: 0.0
TEST:
  THRESH: 0.1
  CKP_PATH: 'weights/mvor_edge_geometry_reid.pth.tar'
  REID: True
  VIS: False