DATASET:
  TRAIN_DATASET: 'soldiers'
  TEST_DATASET: 'soldiers'
  VIEW_IDS: [0,1,2,3,4,5]
  SAMPLING_RANGE: [5, 20]
  ALPHA: 0.1
TRAIN:
  BATCH_SIZE: 1
  BEGIN_EPOCH: 0
  END_EPOCH: 320
  RESUME: False
  CKP_PATH: ''
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP: [240]
  EDGE_ASSOCIATION: False
  REID: False
  GT_BOX: False
  THRESH: 0.0
TEST:
  THRESH: 0.0
  CKP_PATH: 'weights/soldiers_geometry.pth.tar'
  REID: False
  VIS: False