DATASET:
  TRAIN_DATASET: 'wildtrack'
  TEST_DATASET: 'wildtrack'
  VIEW_IDS: [0,1,2,3,4,5,6]
  SAMPLING_RANGE: [5, 20]
  ALPHA: 0.1
TRAIN:
  BATCH_SIZE: 1
  BEGIN_EPOCH: 0
  END_EPOCH: 1200
  RESUME: False
  CKP_PATH: ''
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP: [900]
  EDGE_ASSOCIATION: True
  REID: True
  GT_BOX: False
  THRESH: 0.0
TEST:
  THRESH: 0.4
  CKP_PATH: 'weights/wildtrack_edge_geometry_reid.pth.tar'
  REID: True
  VIS: False